spring.application.name=order-service

server.port=${PORT:8083}


# PostgreSQL

spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://localhost:5435/orderdb}
spring.datasource.username=${ORDER_DB_USERNAME:postgres}
spring.datasource.password=${ORDER_DB_PASSWORD}


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Eureka service registry

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Kafka broker

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}


# Kafka topic

spring.kafka.topic=${KAFKA_ORDER_TOPIC:order-events}
spring.kafka.template.default-topic=${KAFKA_ORDER_TOPIC:order-events}


# Kafka producer serialization

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Kafka reliability

spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.retry.backoff.ms=1000


# Kafka Admin

spring.kafka.admin.properties.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}


# Aiven Kafka security

spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:}" password="${KAFKA_PASSWORD:}";
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=/etc/secrets/ca.pem